### ISSUE TITLE
http://www.grpc.io/docs/tutorials/basic/go.html references codegen.sh which does not exist

### ISSUE THREAD

**Issue by hsaliak** [grpc/grpc.github.io#119]
Following steps in http://www.grpc.io/docs/tutorials/basic/go.html until we are asked to run codegen.sh
This script is not pulled in via any of the previous commands.
We need to remove references to it. /cc @iamqizhao

**Comment by LisaFC** [comment]
Aaaaaanyone?

**Comment by LisaFC** [comment]
Pinnnnnng?

**Comment by jtattermusch** [comment]
@menghanl , can you please address as part of the fixit?

**Comment by menghanl** [comment]
I think this have been fixed by https://github.com/grpc/grpc.github.io/commit/a03ca8a8b7558bbdf90d659f03fdda1fd3c09a3d

And searching for `codegen` on https://grpc.io/docs/tutorials/basic/go.html gives me nothing.
