### ISSUE TITLE
There's been drift between spec & site doc

### ISSUE THREAD

**Issue by louiscryan** [grpc/grpc.github.io#133]
https://github.com/grpc/grpc/blob/master/doc/PROTOCOL-HTTP2.md

vs

https://github.com/grpc/grpc.github.io/blob/master/docs/guides/wire.md

In general we should decide how we want to maintain these. Happy to replicate changes

**Comment by louiscryan** [comment]
@LisaFC

**Comment by LisaFC** [comment]
Ok, I'll take a look. My preference is to just remove the one in the code repo and just maintain the site one, but if there are strong preferences otherwise we'll need to keep them in sync.

**Comment by LisaFC** [comment]
Anyone have any strong preferences here? @hsaliak? Other interested parties (please add them)? Otherwise I'm tempted to just sync them then remove the repo version....
