### ISSUE TITLE
Document single argument and return for methods

### ISSUE THREAD

**Issue by ejona86** [grpc/grpc.github.io#142]
People coming to proto for the first time probably expect methods to be able to receive multiple arguments and possibly even able to return multiple. We should have a small bit of info about how having a single message in each direction isn't truly limiting since you add "arguments" as fields of that message. That could also be part of a "best practices", since it allows you to add fields over time.

**Comment by LisaFC** [comment]
Oh, that's a good idea. I can add that to the Overview - probably under Defining a service.
