### ISSUE TITLE
Fill up error handling and debugging section in grpc.io docs

### ISSUE THREAD

**Issue by zinuga** [grpc/grpc.github.io#153]

**Comment by zinuga** [comment]
@jayantkolhe who can own this?

**Comment by LisaFC** [comment]
I'm happy to get started on this ASAP once I actually get some content/someone to annoy with questions....

**Comment by LisaFC** [comment]
Aaaaaaaanyone?

**Comment by jayantkolhe** [comment]
@a11r  can you please work with Lisa?

**Comment by LisaFC** [comment]
Ping! :) @a11r 

I've got this much so far but the beginning is a bit hand-wavey: http://lcarey0-l.dub.corp.google.com:4000/docs/guides/error.html

I'll send a proper PR for review once I know I'm going in the right direction.
