### ISSUE TITLE
Broken link in Go tutorial

### ISSUE THREAD

**Issue by VcamX** [grpc/grpc.github.io#164]
The link of `.proto` file is broken in [Defining the service](http://www.grpc.io/docs/tutorials/basic/go.html#defining-the-service) section.

**Comment by LisaFC** [comment]
Ah, sorry, didn't see your PR, I've just fixed it in https://github.com/grpc/grpc.github.io/pull/166

**Comment by VcamX** [comment]
@LisaFC That's OK :smile:
