### ISSUE TITLE
Add presentations and talks section to grpc.io

### ISSUE THREAD

**Issue by zinuga** [grpc/grpc.github.io#177]

**Comment by LisaFC** [comment]
Do you have any content for this? Any ideas about where it should live in the current structure (top-level nav item like Documentation and Blog, maybe?)?

**Comment by zinuga** [comment]
I would like to add on homepage below the fold for now with a standard embed size (till we do a redesign). Can include two sections for now: 
Talks: 
https://www.youtube.com/watch?v=sZx3oZt7LVg
https://www.youtube.com/watch?v=-2sWDr3Z0Wo

Presentations
https://docs.google.com/presentation/d/18HIWXt4_JhYFYpg1CT8qC8yNMPP6sGKZX07uwMFebLI/edit#slide=id.gdee976459_2_414

**Comment by LisaFC** [comment]
I can add that for you if you like.

**Comment by LisaFC** [comment]
I don't think that presentation is visible outside Google, can you check?

**Comment by LisaFC** [comment]
Looks a bit like this so far...
http://lcarey0-l.dub.corp.google.com:4000/

**Comment by zinuga** [comment]
May be we split into 3 parts and have clear titles to parts and contents in
them.

Talks:

   1. gRPC Go at Gotham 2015
   2. Microservices with gRPC and Kubernetes:
   https://www.youtube.com/watch?v=UOIJNygDNlE

Presentations

   1. gRPC Overview: http://www.slideshare.net/VarunTalwar4/grpc-overview
   2. gRPC Design and Implementation: Use this:
   http://www.slideshare.net/VarunTalwar4/grpc-design-and-implementation

Case Studies

   1. Square: Story of Microservices at Square: Watch Video button:

Also, if we can add all links like twitter handle, mail link, stackoverflow
link, github link all in footer like kubernetes that will be great.



On Tue, May 3, 2016 at 8:33 AM, LisaFC <notifications@github.com> wrote:

> Looks a bit like this so far...
> http://lcarey0-l.dub.corp.google.com:4000/
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/grpc/grpc.github.io/issues/177#issuecomment-216567994>
>



-- 
"If you dont build your dreams, someone will hire you to build theirs"

**Comment by hsaliak** [comment]
@zinuga I see that the presentations are updated, if you are happy with the current state, please close this issue.

**Comment by zinuga** [comment]
Closing since we have it done in the new GA branch.
