### ISSUE TITLE
Add a section about gRPC performance and link to gRPC performance dashboard (once ready)

### ISSUE THREAD

**Issue by jtattermusch** [grpc/grpc.github.io#179]
We are currently working on populating the performance dashboard (it is not ready yet), but just to get an idea, this is how approx. it is going to look like: 
https://performance-dot-grpc-testing.appspot.com/explore?dashboard=5760820306771968

**Comment by jtattermusch** [comment]
CC @hsaliak

**Comment by LisaFC** [comment]
Would we have this as a separate doc in the Guides or Reference section, do you think?

**Comment by jtattermusch** [comment]
Yes, I think it should be in the Guides section.  What it should contain (just a braindump of some of my thoughts).

1. Some statement about what we are trying to achieve (that gRPC is supposed to be high-performance, low-overhead and should work well under heavy-load situation). We might also mentions that google is planning to use gRPC internally to run its production services.

2. A paragraph about how we measure, link to performance dashboard, link to a performance REAME.md (doesn't exist yet).

**Comment by jtattermusch** [comment]
CC @vjpai

**Comment by LisaFC** [comment]
OK, do you want to try to put together some rough information and then I can turn it into something nice and shiny for the site?

**Comment by jtattermusch** [comment]
@vjpai can you try to put together some basic info?

**Comment by vjpai** [comment]
Current multi-language dashboard is at 
https://performance-dot-grpc-testing.appspot.com/explore?dashboard=5760820306771968

**Comment by hsaliak** [comment]
@vjpai we need performance numbers for the existing v1.0.x branch, so that users see the performance characteristics for the stable release. Given that it may see lesser commits than master, an alternative representation such as a table of benchmarks with %tile numbers may be sufficient.
/cc @jayantkolhe 
I believe that @adelez is working on this?

**Comment by adelez** [comment]
Yes, I'm working with sreek@ on this. Already uploaded data for 32core
tests but seeing failures for 8core. Investigating.

**Comment by adelez** [comment]
Here is the dashboard:
https://performance-dot-grpc-testing.appspot.com/explore?dashboard=5738600293466112&widget=952298825&container=846542667

**Comment by hsaliak** [comment]
Thanks @adelez can we represent the data in any other format (Eg: a table) given that we may not get pull requests that often into the 1.0 branch? 
Also @vjpai would you be providing a short write up that accompanies?

**Comment by adelez** [comment]
Recreated the GA dashboard at
https://performance-dot-grpc-testing.appspot.com/explore?dashboard=5712453606309888&widget=1747498211&container=897341821

However, Go is still built from the master branch. What's the way to get
the GA build for Go?
The following Python tests are not in the database for some reason, most
like they failed:
python_protobuf_sync_unary_ping_pong
python_to_cpp_protobuf_sync_unary_ping_pong
python_protobuf_sync_streaming_ping_pong

On Tue, Aug 2, 2016 at 3:45 PM, Kailash Sethuraman <notifications@github.com

**Comment by hsaliak** [comment]
@vjpai Ping on this issue -- could you please help with this section?

**Comment by hsaliak** [comment]
@adelez for Go, we will mainly be tracking master and will only have a release tag, so a dynamic performance dashboard on 1.0 is not meaningful there. 
@nathanielmanistaatgoogle can you comment on the failed tests?

@vjpai ETA on the performance section?

**Comment by adelez** [comment]
On Tue, Aug 16, 2016 at 4:24 PM, Kailash Sethuraman <
notifications@github.com> wrote:

> @adelez <https://github.com/adelez> for Go, we will mainly be tracking
> master and will only have a release tag, so a dynamic performance dashboard
> on 1.0 is not meaningful there.
>
I'll remove Go from the GA perf test and dashboard.

**Comment by nathanielmanistaatgoogle** [comment]
@hsaliak: not without more information. @adelez: do you have logs or output or anything else from the Python tests?

**Comment by adelez** [comment]
The python tests are passing now.

On Tue, Aug 16, 2016 at 5:32 PM, Nathaniel Manista <notifications@github.com

**Comment by hsaliak** [comment]
Fixed by #331
