### ISSUE TITLE
Remove deprecated scoped credentials examples from auth.md

### ISSUE THREAD

**Issue by LisaFC** [grpc/grpc.github.io#180]
This approach is described in the Examples section as no longer recommended and, per @jboeuf, the snippets just add "noise" to the doc.

**Comment by LisaFC** [comment]
Ping?

**Comment by jboeuf** [comment]
@LisaFC sorry for the delay...

@jtattermusch how do you feel about this? I'm personally all for it but you had some reservations for certain use cases if I remember correctly.

**Comment by jtattermusch** [comment]
Ok, let's do this.
