### ISSUE TITLE
Misleading Java tutorial on client-side streaming

### ISSUE THREAD

**Issue by ByteFlinger** [grpc/grpc.github.io#183]
Hi

I have been trying out the tutorials and the framework in general and noticed that when I implement the client side of a client streaming service (as pointed here http://www.grpc.io/docs/tutorials/basic/java.html), the onNext method never gets called. 

On the site we see the following implementation

````
@Override
      public void onNext(RouteSummary summary) {
        info("Finished trip with {0} points. Passed {1} features. "
            + "Travelled {2} meters. It took {3} seconds.", summary.getPointCount(),
            summary.getFeatureCount(), summary.getDistance(), summary.getElapsedTime());
      }
````

However in my tests this never gets called (which I suppose is OK since the answer itself is not a stream and is only received once, when the server calls onNext followed by onComplete).

If this is correct, maybe make the tutorial a bit clearer by removing  the code in there and place a comment on it? Otherwise what am I missing here?

**Comment by hsaliak** [comment]
I tried to reproduce this issue and noticed that onNext is indeed called. 
Given all the examples, I found it helpful to prefix the info line I was looking for with a "calling onNext:" 
ie: info("calling onNext: Finished..

On the server side, onNext will be called for each time a point is sent to it.

Perhaps your logging is not configured to display info level messages?

**Comment by ByteFlinger** [comment]
Sorry, I was supposed to have commented. You are correct in that I think it was a mistake on my side. Thanks
