### ISSUE TITLE
http://www.grpc.io/posts/ has no rss feed

### ISSUE THREAD

**Issue by zellyn** [grpc/grpc.github.io#193]
Interestingly, it has an rss icon. Which somehow makes the lack of feeds worse.

**Comment by hsaliak** [comment]
Thanks for filing the issue -- we will remove the icon in an upcoming site revamp. 

Do let us know if you feel strongly about providing an RSS feed, we do not have plans to do so at the moment but can consider if this would be useful to have.

**Comment by jtattermusch** [comment]
seems fixed (and the original page doesn't exist anymore).
