### ISSUE TITLE
Update docs with new tools installation commands

### ISSUE THREAD

**Issue by LisaFC** [grpc/grpc.github.io#202]
Need to update docs along with release 0.14 to cover new simplified tools/protoc & plugin installation.

This will largely affect the Overview, though we also need to make sure all the READMEs/installation docs are up to date.

I can work on this myself but may need some help - @hsaliak, @murgatroid99, @jtattermusch, anyone else?

**Comment by hsaliak** [comment]
We need update docs for Python, Ruby and Node at the minimum. 

We need to update the top level INSTALL.md's "if you are in a hurry" section to reference these tools for some of the wrapped languages /cc @stanley-cheung would you be able to help with that?

@LisaFC I can review this PR..
