### ISSUE TITLE
docs/guides/auth.html has broken fragments

### ISSUE THREAD

**Issue by ejona86** [grpc/grpc.github.io#205]
Because multiple headers are identical (but in different sections), it seems they end up being the same fragment. This seems like a pretty fundamental bug in the software that produces the ids (probably not in our markup).

For example click Java's "Base case - no encryption or authentication". It will have the same URL as Ruby's (and since Ruby is first in the document, you will be taken to Ruby's docs).

http://www.grpc.io/docs/guides/auth.html#base-case-no-encryption-or-authentication

**Comment by LisaFC** [comment]
Yes, I noticed that earlier - the autogenerated TOC thing is done with some fairly simple Javascript I found here: https://github.com/ghiculescu/jekyll-table-of-contents

I'll see what I can do to fix it, may involve either updating the script or adding some kind of manual anchors.

**Comment by jtattermusch** [comment]
Any updates here?

**Comment by LisaFC** [comment]
Going to try and fix it today...

**Comment by LisaFC** [comment]
Seems to be already fixed as the links in the TOC now go to different URLs for each language section.
