### ISSUE TITLE
Outdated snippets for Java tutorial

### ISSUE THREAD

**Issue by ejona86** [grpc/grpc.github.io#209]
The [Java tutorial](http://www.grpc.io/docs/tutorials/basic/java.html) is now a bit out-of-date compared to the examples that they link to. It is still "correct," but doesn't make it as obvious how we would encourage error handling. It seems I'm at fault for not getting the docs updated when I did [my error-handling commit](https://github.com/grpc/grpc-java/commit/df310fe2b5a02f99e2a04cc69a4c0434fbe66f0b).

**Comment by LisaFC** [comment]
Is it the text that's out of date, or the snippets, or both? Do you want to do a rough update and I can review?

**Comment by ejona86** [comment]
I didn't read over the text to check, but I assume the text is still approximately right. I can do a rough update, although I'm concerned about having enough time before GA, so I might try to pass it off.

**Comment by ejona86** [comment]
This was fixed by #280.
