### ISSUE TITLE
update markdown engine to kramdown

### ISSUE THREAD

**Issue by dgquintas** [grpc/grpc.github.io#218]
> You are currently using the 'redcarpet' Markdown engine, which is no longer supported by GitHub Pages and may cease working at any time. To ensure your site continues to build, remove the 'markdown' setting in your site's '_config.yml' file and confirm your site renders as expected. For more information, see https://help.github.com/articles/updating-your-markdown-processor-to-kramdown.

**Comment by hsaliak** [comment]
@zinuga can this be addressed as part of the website revamp?

**Comment by dgquintas** [comment]
Here's my WIP set of changes up to the point when I gave up. `index.md` is in a bad shape due to its faulty html (unclosed tags, mostly <p> and <li>) and its mixture of markdown and html. This confuses the new parser. I've fixed some: https://github.com/grpc/grpc.github.io/pull/219

**Comment by LisaFC** [comment]
The mixture of Markdown and HTML in that page was/is an unfortunate consequence of the Markdown engine getting confused by the tab divs when I added the tabs - it simply wasn't rendering some of the tab contents at all (goes off muttering about the evils of Markdown). The fact that I only turned some of them into raw HTML and the unclosed tags are purely my sloppy/hasty editing.... 

Thanks for taking a look at this, I had thought it still rendered ok with kramdown but seemingly not. I can finish your update as even though we're revamping the site we're going to be reusing most of this content...

**Comment by LisaFC** [comment]
Oh, FUNTIMES, the Kramdown parser is so fussy with HTML that instead of just not showing bits of code that accidentally look like HTML elements (eg std::unique_ptr<Parser>) it actually craps out completely any time it encounters a < or > that isn't HTML, even if it doesn't have a matching > or < and hence would render fine in normal HTML. I'll get this finished today, hopefully with what remains of my sanity...

**Comment by dgquintas** [comment]
what about using &lt and &gt in lieu of < and >?

**Comment by LisaFC** [comment]
That's what I've done. It's just a matter of finding them amongst the HTML....

Have a fix ready, just need to sort out some merging issues.

**Comment by LisaFC** [comment]
Fixed in https://github.com/grpc/grpc.github.io/pull/225
