### ISSUE TITLE
Load Balancing best practice doc on website

### ISSUE THREAD

**Issue by zinuga** [grpc/grpc.github.io#232]
We need to have a load balancing best practices/how to doc on our website for users deciding on how to do load balancing with gRPC

**Comment by hsaliak** [comment]
@dgquintas Would you be able to provide a document on how to use the current API hooks to get users started on load balancing with gRPC?  
What we need is something at a "block diagram" level that uses our load reporting API to conceptualize a simple load balancer.

**Comment by dgquintas** [comment]
Those features are not part of GA. I'm happy to put together such a doc, but the only LB mechanisms available in the GA release are Pick First and Round Robin. There's no load reporting and no `grpclb` (ie, the "external load balancing service" described in https://github.com/grpc/grpc/blob/master/doc/load-balancing.md). There's also no way in GA to choose between Pick First and Round Robin. That'll come with the implementation of Client Config, one of this quarter's KRs.

What I can do is describe what we want to accomplished, as opposed to what we are actually shipping in code for GA.

**Comment by hsaliak** [comment]
I see -- would be good to at least describe the current state and what's available, as more features come through in this space, we can add them to the doc. Pick First vs Round Robin -- if we cannot chose, whats the default?

**Comment by zinuga** [comment]
And more importantly describe what user needs to do, what we do in client, server and balancer side to do even PickFirst or RoundRobbin.

**Comment by dgquintas** [comment]
The default is Pick First and there's no (publicly available) way to choose :) 

With all this, do we still want to write anything now? It'd mostly be a "what's coming", augmenting the aforementioned load-balancing.md doc.

**Comment by zinuga** [comment]
dgq and I spoke and we agreed on scope

**Comment by hsaliak** [comment]
Could you please persist that in this issue :)

**Comment by dgquintas** [comment]
The consensus (after also talking to @a11r) is to expand https://github.com/grpc/grpc/blob/master/doc/load-balancing.md with some more details, specifically a visual diagram of the high level architecture. I'm working on this right now.

In any event, this should not have the GA tag, as it's unrelated.

**Comment by dgquintas** [comment]
see https://github.com/grpc/grpc/pull/7294
