### ISSUE TITLE
Contribution guidelines doc to be written up

### ISSUE THREAD

**Issue by zinuga** [grpc/grpc.github.io#233]

**Comment by hsaliak** [comment]
Update https://github.com/grpc/grpc.github.io/blob/master/contribute/index.html with the latest information.

**Comment by hsaliak** [comment]
@zinuga ping on this issue.  The contribution guidelines are still very generic.

**Comment by zinuga** [comment]
https://github.com/grpc/grpc.github.io/pull/316

**Comment by hsaliak** [comment]
Closing this with #316
