### ISSUE TITLE
Samples content for new website

### ISSUE THREAD

**Issue by zinuga** [grpc/grpc.github.io#235]

**Comment by hsaliak** [comment]
- [ ] Check and verify secure hello world, streaming hello world. Implemented only in Go for GA. 
- [ ] Check and verify sample on streaming on iOS using an external API /cc @timburks 
- [ ] Android mobile json vs grpc benchmark samples @makdharma is it worth linking here?
- [ ] Link to the samples from github. @LisaFC 
- [ ] Metadata usage sample in at least 1 language.  @hsaliak

**Comment by zinuga** [comment]
Secure Hello World in Go
https://github.com/kelseyhightower/helloworld
Tim's sample: https://github.com/GoogleCloudPlatform/ios-docs-samples/tree/master/speech/Objective-C/Speech-gRPC-Streaming

**Comment by hsaliak** [comment]
@zinuga could you please update if the samples are already linked to or  send in the pull request to link to the right samples?

**Comment by zinuga** [comment]
https://github.com/grpc/grpc.github.io/pull/304 to address samples

**Comment by hsaliak** [comment]
Closing this since #304 is merged.
