### ISSUE TITLE
Update FAQ for GA

### ISSUE THREAD

**Issue by zinuga** [grpc/grpc.github.io#236]

**Comment by hsaliak** [comment]
- [ ] Review current FAQ and update the answers as necessary @zinuga 
- [ ] Check if new questions need to be added. @zinuga 
- [ ] Update FAQ @LisaFC

**Comment by zinuga** [comment]
Reviewed FAQ and edited responses.
https://github.com/grpc/grpc.github.io/pull/249

**Comment by hsaliak** [comment]
The pull request in #249 has some merge requests that need to be resolved.

**Comment by hsaliak** [comment]
#249 is merged, closing this issue.
