### ISSUE TITLE
Refresh Quickstart content for website. 

### ISSUE THREAD

**Issue by hsaliak** [grpc/grpc.github.io#237]
- [x] Volunteers for every language. 
- [x] Review content, provide PRs if necessary.

**Comment by LisaFC** [comment]
We now have a Python quickstart in this PR that should be used as a model for the other languages: https://github.com/grpc/grpc.github.io/pull/223

Preview here: https://github.com/LisaFC/grpc.github.io/blob/quickstarts/docs/quickstarts/python-quickstart.md

**Comment by zinuga** [comment]
- [ ] @murgatroid99 can you do node and ruby?
- [ ] @nicolasnoble C++?
- [ ] @ejona86 java?

Lets follow the python template and get this done

**Comment by zinuga** [comment]
- [ ] @apolcyn for C#

**Comment by ejona86** [comment]
Does the quickstart replace the tutorial? Or is it in addition?

**Comment by LisaFC** [comment]
It's in addition - the idea is that it's for someone who wants to dive straight in and DO SOMETHING, without much explanation, just letting them complete a proper task. Then they look at the tutorial for a walk through with all the context information and links.

I have shamelessly stolen this idea from cloud.google.com's doc template and UX research...

**Comment by murgatroid99** [comment]
Node is unusual here because it has two different kinds of code generation. Dynamic code generation is simpler/easier to use, but static code generation has a workflow and interface more consistent with how this will work in other languages. Which should my Node quickstart guide cover?

**Comment by hsaliak** [comment]
Do we want users to eventually move to the static flow, if so we should
just cover that here so that we do not have to come back and update the
guide later.

If we want to leave the static code generation flow as an advanced feature
and let most users just do dynamic code generation, then i think the latter
is sufficient.

**Comment by murgatroid99** [comment]
I think that if we want the reader to get something up and running quickly and relatively easily, dynamic codegen works better for that. I'm not exactly sure if we want all users to switch to static codegen, but I don't think we intend to remove the dynamic codegen anytime soon. Plus, switching won't be a ton of work, so, I'll go with dynamic codegen for now.

**Comment by murgatroid99** [comment]
Also, should these quickstart guides go into the GA branch or the master branch?

**Comment by hsaliak** [comment]
They should go into the GA branch.

**Comment by apolcyn** [comment]
C# draft here https://github.com/grpc/grpc/pull/7515. Greeter and route_guide examples seemed to need to be updated too, with https://github.com/grpc/grpc/pull/7514.

**Comment by zinuga** [comment]
@dgquintas for C++ quickstart
Reiterating that quickstarts should include "updating a grpc service" by way of adding a method to hello world proto and using it.

**Comment by apolcyn** [comment]
For C# quickstart.

Because of the pending change that breaks IDE usage on mac and linux, in PR https://github.com/grpc/grpc/pull/7519, I will have to update the quickstart, and possibly the examples, with workarounds for using them on mac and linux.

**Comment by hsaliak** [comment]
Update: The only remaining merge is for C#, all other content should be in.

**Comment by hsaliak** [comment]
Fixed, all quickstarts are in. Closing.
