### ISSUE TITLE
Strike "more reference documentation is coming soon"

### ISSUE THREAD

**Issue by nathanielmanistaatgoogle** [grpc/grpc.github.io#296]
Currently these words appear in at least the Python tutorial. I suspect they should all be struck before 1.0.0?

**Comment by hsaliak** [comment]
Agreed, we should strike out forward looking statements. They are better tracked in the issue tracker. 
Assigning to @LisaFC

**Comment by LisaFC** [comment]
Yes, I think most of them date from our first release when we had only the bare basics of documentation and we were emphasising how much more we were going to provide in future, they can definitely go now.
