### ISSUE TITLE
Tutorial link to "the Python quick start guide" should link to new Tutorial on grpc.io, not old tutorial in grpc code repository

### ISSUE THREAD

**Issue by nathanielmanistaatgoogle** [grpc/grpc.github.io#297]
The link at the bottom of [this section](https://github.com/grpc/grpc.github.io/blob/063f6be8c01a3377c4c2a5d724a32403bdb0751a/docs/tutorials/basic/python.md#example-code-and-setup). Also I think "quick start" is now one word in the new content?

**Comment by LisaFC** [comment]
Fixed in https://github.com/grpc/grpc.github.io/pull/300
