### ISSUE TITLE
Blog theme does not work well with full GFM markdown

### ISSUE THREAD

**Issue by pcj** [grpc/grpc.github.io#396]
@hsaliak @zinuga The merge of https://github.com/grpc/grpc.github.io/pull/369 does not look good with this jekyll theme.  

Let's revert this, then create a summary statement for the blog that points to the grpc_greetertimer repo and people can continue to read there.  What do you think?

**Comment by hsaliak** [comment]
@pcj i am working on a PR to fix this. There is an underlying problem with the markdown.
I will send a PR to remove this file but will follow up with an update that solves this problem.

**Comment by hsaliak** [comment]
@pcj it actually works ok when you click through to the 'Read more' but the main page has broken rendering.

**Comment by pcj** [comment]
Pretty much, yes.. A few issues

1. Title looks redundant
2. Image links broken.
3. Date is Sept 6

**Comment by hsaliak** [comment]
Image links do not seem to work across repos. I will move it to my current repo. 
The date is keyed off the file name, so I will git mv it. 
The numbering is formatted poorly and the links in the title break the main page too..

**Comment by pcj** [comment]
There is also no link the repo with the sample code: https://github.com/pubref/grpc_greetertimer

**Comment by pcj** [comment]
OK, that looks better.  Shall I submit a new PR for updated content?  I see two options:

1. Redo the post as a short summary with link to main content (as a README in the [grpc_greetertimer repo](https://github.com/pubref/grpc_greetertimer) github repo).

2. Adapt the full post to look better with your theme.

**Comment by hsaliak** [comment]
@pcj I have a PR on the way that does this.. I made slight modifications. I also added the  tag so that the post clicks through to the fully expanded post so we do not have to wrestle with the formatting too much.

The main blog page will look like the attached image.
![image](https://cloud.githubusercontent.com/assets/150108/19089817/c44ccbe4-8a30-11e6-8035-7595734cf327.png)
