### ISSUE TITLE
C++ tutorials are pointing to v1.0.0 which does not build

### ISSUE THREAD

**Issue by aurelienrb** [grpc/grpc.github.io#415]
Hello,

Following the discussion [here](https://github.com/grpc/grpc/issues/8606), I followed the instruction on the website to build and use grpc++. I spent almost 2 days struggling with linker errors before finding that the issue is in grpc++ itlsef and learning that the v1.0.0 just can't be built successfully.

In other words, if a beginner follows the instruction on the website, (s)he will fail to successfully build any c++ example :-(

So I suggest to update the website to stop mentionning version v1.0.0 (like [here](http://www.grpc.io/docs/quickstart/cpp.html)) and to update the version returned by http://grpc.io/release with something that works for grpc++ (as mentioned [here](https://github.com/grpc/grpc/blob/master/INSTALL.md)). I switched to v1.0.x and now it works fine.

Aurelien

**Comment by hsaliak** [comment]
@aurelienrb thanks for flagging this. It's a valid problem with a simple fix. @LisaFC would you be able to pick this one up?

**Comment by hsaliak** [comment]
@LisaFC ping

**Comment by LisaFC** [comment]
Sorry this fell off my to-do list, I can fix it today - should we update the global release value for the site to 1.0.1? Will that work for all language implementations?

**Comment by pulkitsharma07** [comment]
@LisaFC, @aurelienrb I think this issue can be closed, as the documentation no longer specifies a particular version to clone.
