### ISSUE TITLE
grpc.io https

### ISSUE THREAD

**Issue by tbillington** [grpc/grpc.github.io#433]
When I try to visit https://www.grpc.io/ or https://grpc.io/ I'm getting `net::ERR_CERT_COMMON_NAME_INVALID`.

Seems https isn't working for the website.

**Comment by hsaliak** [comment]
@tbillington we host the site off github pages, and this is a known issue with serving github pages off custom domains.

**Comment by jtattermusch** [comment]
This was fixed a while ago by @mehrdada .
