### ISSUE TITLE
Where is the language reference or grammar for a service definition?

### ISSUE THREAD

**Issue by cliffbdf** [grpc/grpc.github.io#438]
It would be really helpful to have a normative reference for service definitions. Thanks!

**Comment by hsaliak** [comment]
@cliffbdf could you elaborate further?  We currently support the use of protocol buffers to define gRPC services and their documentation is here: https://developers.google.com/protocol-buffers/docs/proto3

Is that what you were looking for? Could you provide more details around what you are looking for?
If it is indeed the documentation for procol buffers, how / where can we link to it more prominently?

**Comment by cliffbdf** [comment]
Yes, I saw that, but messages are only part of a service specification - I was not able to find a normative reference for a service definition, including the methods that it defines.

Best regards,

Cliff

**Comment by hsaliak** [comment]
There is a small section on defining services here:
https://developers.google.com/protocol-buffers/docs/proto3#services
But i do agree that it is barebones and does to pass as normative.

https://github.com/grpc/grpc/tree/master/examples/protos has proto examples that you can refer in the meanwhile..

Would updating and improving the section above to ensure that it is normative resolve your concerns?

**Comment by cliffbdf** [comment]
Actually I did not see that - since protocol buffers is the underlying transport for gRPC, it is unexpected that service definitions would be documented in Protocol Buffers. But the guide is decent. Still, it leaves questions unanswered that a normative definition/guide would: e.g., in some examples I have seen, there are curly braces {} following an rpc prototype, but the example in the guide does not have {} - why? It would be nice to have an actual grammar definition, with each possible branch/option defined. Overall the guide is good though, and the underlying technology (gRPC and PB) looks awesome!

Very best,

Cliff

**Comment by cliffbdf** [comment]
Hi Kailash - has the protoc compiiler been changed to generate different output?

When I run it,

protoc —java_out=my_dir TaskEngine.proto

with this proto file (TaskEngine.proto),

syntax = "proto3";

option java_multiple_files = true;
option java_package = "scaledmarkets.piper";
option java_outer_classname = "TaskEngine";

package piper;

service TaskEngineServant {
    rpc ping(Request) returns (Response) {}
}

message Request {
}

message Response {
    string message = 1;
}

it generates the following files:

Request.java
RequetOrBuilder.java
Response.java
ResponseOrBuilder.java
TaskEngine.java

Yes, the documentation <http://www.grpc.io/docs/tutorials/basic/java.html> says that it should generate something like,

TaskEngineGrpc.java, containing TaskEngineGrpc.TaskEngineImplBase.


Best regards,

Cliff

**Comment by ericgribkoff** [comment]
You need to tell protoc about the gRPC Java plugin in order to get the `TaskEngineGrpc.java` output.

From the `grpc-java/compiler/` directory, run this to generate the plugin:

`../gradlew java_pluginExecutable`

And invoke with:

`protoc --plugin=protoc-gen-grpc-java=/path/to/grpc-java/compiler/build/exe/java_plugin/protoc-gen-grpc-java   --grpc-java_out=.  "TaskEngine.proto"`

See https://github.com/grpc/grpc-java/blob/master/compiler/README.md for more details.

**Comment by cliffbdf** [comment]
Thanks for this info. I would not have looked there. But the build of the plugin failed on my Mac. The error was,

/Users/cliffordberg/Library/grpc-java-1.1.2/compiler/src/java_plugin/cpp/java_generator.h:8:10: fatal error: 'google/protobuf/io/zero_copy_stream.h' file not found


It might be good to publish the binary with each release of the plugin, so that users of the compiler don’t have to build the compiler first. Here is the full output:

Clifford-Bergs-MacBook-Pro:compiler cliffordberg$ ../gradlew java_pluginExecutable
Downloading https://services.gradle.org/distributions/gradle-3.2-bin.zip
.................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................
Unzipping /Users/cliffordberg/.gradle/wrapper/dists/gradle-3.2-bin/avantb235jk77byagvnd7aog7/gradle-3.2-bin.zip to /Users/cliffordberg/.gradle/wrapper/dists/gradle-3.2-bin/avantb235jk77byagvnd7aog7
Set executable permissions for: /Users/cliffordberg/.gradle/wrapper/dists/gradle-3.2-bin/avantb235jk77byagvnd7aog7/gradle-3.2/bin/gradle
Starting a Gradle Daemon (subsequent builds will be faster)
Download https://repo1.maven.org/maven2/com/google/gradle/osdetector-gradle-plugin/1.4.0/osdetector-gradle-plugin-1.4.0.pom
Download https://repo1.maven.org/maven2/kr/motd/maven/os-maven-plugin/1.4.0.Final/os-maven-plugin-1.4.0.Final.pom
Download https://repo1.maven.org/maven2/org/apache/maven/maven-plugin-api/3.2.1/maven-plugin-api-3.2.1.pom
Download https://repo1.maven.org/maven2/org/apache/maven/maven/3.2.1/maven-3.2.1.pom
Download https://repo1.maven.org/maven2/org/codehaus/plexus/plexus-utils/3.0.17/plexus-utils-3.0.17.pom
Download https://repo1.maven.org/maven2/org/apache/maven/maven-model/3.2.1/maven-model-3.2.1.pom
Download https://repo1.maven.org/maven2/org/apache/maven/maven-artifact/3.2.1/maven-artifact-3.2.1.pom
Download https://repo1.maven.org/maven2/org/eclipse/sisu/org.eclipse.sisu.plexus/0.0.0.M5/org.eclipse.sisu.plexus-0.0.0.M5.pom
Download https://repo1.maven.org/maven2/org/eclipse/sisu/sisu-plexus/0.0.0.M5/sisu-plexus-0.0.0.M5.pom
Download https://repo1.maven.org/maven2/javax/enterprise/cdi-api/1.0/cdi-api-1.0.pom
Download https://repo1.maven.org/maven2/org/jboss/weld/weld-api-parent/1.0/weld-api-parent-1.0.pom
Download https://repo1.maven.org/maven2/org/jboss/weld/weld-api-bom/1.0/weld-api-bom-1.0.pom
Download https://repo1.maven.org/maven2/org/jboss/weld/weld-parent/6/weld-parent-6.pom
Download https://repo1.maven.org/maven2/com/google/guava/guava/10.0.1/guava-10.0.1.pom
Download https://repo1.maven.org/maven2/com/google/guava/guava-parent/10.0.1/guava-parent-10.0.1.pom
Download https://repo1.maven.org/maven2/org/sonatype/sisu/sisu-guice/3.1.0/sisu-guice-3.1.0.pom
Download https://repo1.maven.org/maven2/org/sonatype/sisu/inject/guice-parent/3.1.0/guice-parent-3.1.0.pom
Download https://repo1.maven.org/maven2/org/eclipse/sisu/org.eclipse.sisu.inject/0.0.0.M5/org.eclipse.sisu.inject-0.0.0.M5.pom
Download https://repo1.maven.org/maven2/org/eclipse/sisu/sisu-inject/0.0.0.M5/sisu-inject-0.0.0.M5.pom
Download https://repo1.maven.org/maven2/org/codehaus/plexus/plexus-classworlds/2.4/plexus-classworlds-2.4.pom
Download https://repo1.maven.org/maven2/javax/annotation/jsr250-api/1.0/jsr250-api-1.0.pom
Download https://repo1.maven.org/maven2/com/google/gradle/osdetector-gradle-plugin/1.4.0/osdetector-gradle-plugin-1.4.0.jar
Download https://repo1.maven.org/maven2/kr/motd/maven/os-maven-plugin/1.4.0.Final/os-maven-plugin-1.4.0.Final.jar
Download https://repo1.maven.org/maven2/org/apache/maven/maven-plugin-api/3.2.1/maven-plugin-api-3.2.1.jar
Download https://repo1.maven.org/maven2/org/codehaus/plexus/plexus-utils/3.0.17/plexus-utils-3.0.17.jar
Download https://repo1.maven.org/maven2/org/apache/maven/maven-model/3.2.1/maven-model-3.2.1.jar
Download https://repo1.maven.org/maven2/org/apache/maven/maven-artifact/3.2.1/maven-artifact-3.2.1.jar
Download https://repo1.maven.org/maven2/org/eclipse/sisu/org.eclipse.sisu.plexus/0.0.0.M5/org.eclipse.sisu.plexus-0.0.0.M5.jar
Download https://repo1.maven.org/maven2/javax/enterprise/cdi-api/1.0/cdi-api-1.0.jar
Download https://repo1.maven.org/maven2/com/google/guava/guava/10.0.1/guava-10.0.1.jar
Download https://repo1.maven.org/maven2/org/sonatype/sisu/sisu-guice/3.1.0/sisu-guice-3.1.0-no_aop.jar
Download https://repo1.maven.org/maven2/org/eclipse/sisu/org.eclipse.sisu.inject/0.0.0.M5/org.eclipse.sisu.inject-0.0.0.M5.jar
Download https://repo1.maven.org/maven2/org/codehaus/plexus/plexus-classworlds/2.4/plexus-classworlds-2.4.jar
Download https://repo1.maven.org/maven2/javax/annotation/jsr250-api/1.0/jsr250-api-1.0.jar
Download https://repo1.maven.org/maven2/org/kt3k/gradle/plugin/coveralls-gradle-plugin/2.0.1/coveralls-gradle-plugin-2.0.1.pom
Download https://repo1.maven.org/maven2/org/apache/httpcomponents/httpmime/4.3/httpmime-4.3.pom
Download https://repo1.maven.org/maven2/org/apache/httpcomponents/httpcomponents-client/4.3/httpcomponents-client-4.3.pom
Download https://repo1.maven.org/maven2/org/apache/httpcomponents/project/7/project-7.pom
Download https://repo1.maven.org/maven2/org/codehaus/groovy/modules/http-builder/http-builder/0.7.1/http-builder-0.7.1.pom
Download https://repo1.maven.org/maven2/org/apache/httpcomponents/httpclient/4.3/httpclient-4.3.pom
Download https://repo1.maven.org/maven2/net/sf/json-lib/json-lib/2.3/json-lib-2.3.pom
Download https://repo1.maven.org/maven2/net/sourceforge/nekohtml/nekohtml/1.9.16/nekohtml-1.9.16.pom
Download https://repo1.maven.org/maven2/xml-resolver/xml-resolver/1.2/xml-resolver-1.2.pom
Download https://repo1.maven.org/maven2/commons-beanutils/commons-beanutils/1.8.0/commons-beanutils-1.8.0.pom
Download https://repo1.maven.org/maven2/net/sf/ezmorph/ezmorph/1.0.6/ezmorph-1.0.6.pom
Download https://repo1.maven.org/maven2/xerces/xercesImpl/2.9.1/xercesImpl-2.9.1.pom
Download https://repo1.maven.org/maven2/xml-apis/xml-apis/1.3.04/xml-apis-1.3.04.pom
Download https://repo1.maven.org/maven2/org/apache/httpcomponents/httpcore/4.3/httpcore-4.3.pom
Download https://repo1.maven.org/maven2/org/apache/httpcomponents/httpcomponents-core/4.3/httpcomponents-core-4.3.pom
Download https://repo1.maven.org/maven2/commons-logging/commons-logging/1.1.3/commons-logging-1.1.3.pom
Download https://repo1.maven.org/maven2/org/kt3k/gradle/plugin/coveralls-gradle-plugin/2.0.1/coveralls-gradle-plugin-2.0.1.jar
Download https://repo1.maven.org/maven2/org/apache/httpcomponents/httpmime/4.3/httpmime-4.3.jar
Download https://repo1.maven.org/maven2/org/codehaus/groovy/modules/http-builder/http-builder/0.7.1/http-builder-0.7.1.jar
Download https://repo1.maven.org/maven2/org/apache/httpcomponents/httpclient/4.3/httpclient-4.3.jar
Download https://repo1.maven.org/maven2/net/sf/json-lib/json-lib/2.3/json-lib-2.3-jdk15.jar
Download https://repo1.maven.org/maven2/net/sourceforge/nekohtml/nekohtml/1.9.16/nekohtml-1.9.16.jar
Download https://repo1.maven.org/maven2/xml-resolver/xml-resolver/1.2/xml-resolver-1.2.jar
Download https://repo1.maven.org/maven2/commons-beanutils/commons-beanutils/1.8.0/commons-beanutils-1.8.0.jar
Download https://repo1.maven.org/maven2/commons-lang/commons-lang/2.4/commons-lang-2.4.jar
Download https://repo1.maven.org/maven2/net/sf/ezmorph/ezmorph/1.0.6/ezmorph-1.0.6.jar
Download https://repo1.maven.org/maven2/xerces/xercesImpl/2.9.1/xercesImpl-2.9.1.jar
Download https://repo1.maven.org/maven2/xml-apis/xml-apis/1.3.04/xml-apis-1.3.04.jar
Download https://repo1.maven.org/maven2/org/apache/httpcomponents/httpcore/4.3/httpcore-4.3.jar
Download https://repo1.maven.org/maven2/commons-codec/commons-codec/1.6/commons-codec-1.6.jar
Download https://repo1.maven.org/maven2/commons-logging/commons-logging/1.1.3/commons-logging-1.1.3.jar
Download https://plugins.gradle.org/m2/be/insaneprogramming/gradle/animalsniffer-gradle-plugin/1.4.0/animalsniffer-gradle-plugin-1.4.0.pom
Download https://plugins.gradle.org/m2/be/insaneprogramming/gradle/animalsniffer-gradle-plugin/1.4.0/animalsniffer-gradle-plugin-1.4.0.jar
Download https://repo1.maven.org/maven2/org/apache/commons/commons-math3/3.6/commons-math3-3.6.pom
Download https://repo1.maven.org/maven2/org/apache/commons/commons-parent/39/commons-parent-39.pom
Download https://repo1.maven.org/maven2/com/google/protobuf/protobuf-gradle-plugin/0.8.0/protobuf-gradle-plugin-0.8.0.pom
Download https://plugins.gradle.org/m2/gradle/plugin/me/champeau/gradle/jmh-gradle-plugin/0.3.0/jmh-gradle-plugin-0.3.0.pom
Download https://repo1.maven.org/maven2/org/apache/commons/commons-math3/3.6/commons-math3-3.6.jar
Download https://repo1.maven.org/maven2/com/google/protobuf/protobuf-gradle-plugin/0.8.0/protobuf-gradle-plugin-0.8.0.jar
Download https://plugins.gradle.org/m2/gradle/plugin/me/champeau/gradle/jmh-gradle-plugin/0.3.0/jmh-gradle-plugin-0.3.0.jar
The Task.leftShift(Closure) method has been deprecated and is scheduled to be removed in Gradle 5.0. Please use Task.doLast(Action) instead.
        at build_8nzznohhcg3bttwglgwjuqr47$_run_closure1$_closure7$_closure22$_closure24.doCall(/Users/cliffordberg/Library/grpc-java-1.1.2/build.gradle:110)
Download https://repo1.maven.org/maven2/org/mortbay/jetty/alpn/jetty-alpn-agent/2.0.3/jetty-alpn-agent-2.0.3.pom
Download https://repo1.maven.org/maven2/org/eclipse/jetty/jetty-parent/25/jetty-parent-25.pom
Download https://repo1.maven.org/maven2/org/mortbay/jetty/alpn/jetty-alpn-agent/2.0.3/jetty-alpn-agent-2.0.3.jar
*** Building codegen requires Protobuf version 3.1.0
*** Please refer to https://github.com/grpc/grpc-java/blob/master/COMPILING.md#how-to-build-code-generation-plugin
:grpc-compiler:compileJava_pluginExecutableJava_pluginCpp
In file included from /Users/cliffordberg/Library/grpc-java-1.1.2/compiler/src/java_plugin/cpp/java_plugin.cpp:8:
/Users/cliffordberg/Library/grpc-java-1.1.2/compiler/src/java_plugin/cpp/java_generator.h:8:10: fatal error: 'google/protobuf/io/zero_copy_stream.h' file not found
#include <google/protobuf/io/zero_copy_stream.h>
         ^
1 error generated.

/Users/cliffordberg/Library/grpc-java-1.1.2/compiler/src/java_plugin/cpp/java_generator.h:8:10: fatal error: 'google/protobuf/io/zero_copy_stream.h' file not found
#include <google/protobuf/io/zero_copy_stream.h>
         ^
1 error generated.

In file included from /Users/cliffordberg/Library/grpc-java-1.1.2/compiler/src/java_plugin/cpp/java_generator.cpp:1:
/Users/cliffordberg/Library/grpc-java-1.1.2/compiler/src/java_plugin/cpp/java_generator.h:8:10: fatal error: 'google/protobuf/io/zero_copy_stream.h' file not found
#include <google/protobuf/io/zero_copy_stream.h>
         ^
1 error generated.

:grpc-compiler:compileJava_pluginExecutableJava_pluginCpp FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':grpc-compiler:compileJava_pluginExecutableJava_pluginCpp'.
> Multiple build operations failed.
      C++ compiler failed while compiling java_plugin.cpp.
      C++ compiler failed while compiling java_generator.h.
      C++ compiler failed while compiling java_generator.cpp.
  See the complete log at: file:///Users/cliffordberg/Library/grpc-java-1.1.2/compiler/build/tmp/compileJava_pluginExecutableJava_pluginCpp/output.txt

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 4 mins 15.099 secs
Clifford-Bergs-MacBook-Pro:compiler cliffordberg$

**Comment by ericgribkoff** [comment]
What version of protoc is installed? (`protoc --version`). It's also possible you need to specify the search paths for header files and libraries, see https://github.com/grpc/grpc-java/blob/master/COMPILING.md#mac.

**Comment by cliffbdf** [comment]
> On Feb 23, 2017, at 2:10 PM, Eric Gribkoff <notifications@github.com> wrote:
> 
> What version of protoc is installed? (protoc --version). It's also possible you need to specify the search paths for header files and libraries, see https://github.com/grpc/grpc-java/blob/master/COMPILING.md#mac <https://github.com/grpc/grpc-java/blob/master/COMPILING.md#mac>.
> 
protoc version:
libprotoc 3.1.0

I tried setting CXXFLAGS and LDFLAGS as in the notes for mac, but still an error. I am using El Capitan (OSX 10.11.6) - please seel below.

Would you be able to upload a binary for the release? Or send me one? Right now the release only contains a zip of the source code.

Clifford-Bergs-MacBook-Pro:grpc-java-1.1.2 cliffordberg$ ../gradlew java_pluginExecutable
-bash: ../gradlew: No such file or directory
Clifford-Bergs-MacBook-Pro:grpc-java-1.1.2 cliffordberg$ cd compiler
Clifford-Bergs-MacBook-Pro:compiler cliffordberg$ ../gradlew java_pluginExecutable
The Task.leftShift(Closure) method has been deprecated and is scheduled to be removed in Gradle 5.0. Please use Task.doLast(Action) instead.
        at build_8nzznohhcg3bttwglgwjuqr47$_run_closure1$_closure7$_closure22$_closure24.doCall(/Users/cliffordberg/Library/grpc-java-1.1.2/build.gradle:110)
*** Building codegen requires Protobuf version 3.1.0
*** Please refer to https://github.com/grpc/grpc-java/blob/master/COMPILING.md#how-to-build-code-generation-plugin
:grpc-compiler:compileJava_pluginExecutableJava_pluginCpp
/Users/cliffordberg/Library/grpc-java-1.1.2/compiler/src/java_plugin/cpp/java_generator.h:8:10: fatal error: 'google/protobuf/io/zero_copy_stream.h' file not found
#include <google/protobuf/io/zero_copy_stream.h>
         ^
1 error generated.

In file included from /Users/cliffordberg/Library/grpc-java-1.1.2/compiler/src/java_plugin/cpp/java_plugin.cpp:8:
/Users/cliffordberg/Library/grpc-java-1.1.2/compiler/src/java_plugin/cpp/java_generator.h:8:10: fatal error: 'google/protobuf/io/zero_copy_stream.h' file not found
#include <google/protobuf/io/zero_copy_stream.h>
         ^
1 error generated.

In file included from /Users/cliffordberg/Library/grpc-java-1.1.2/compiler/src/java_plugin/cpp/java_generator.cpp:1:
/Users/cliffordberg/Library/grpc-java-1.1.2/compiler/src/java_plugin/cpp/java_generator.h:8:10: fatal error: 'google/protobuf/io/zero_copy_stream.h' file not found
#include <google/protobuf/io/zero_copy_stream.h>
         ^
1 error generated.

:grpc-compiler:compileJava_pluginExecutableJava_pluginCpp FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':grpc-compiler:compileJava_pluginExecutableJava_pluginCpp'.
> Multiple build operations failed.
      C++ compiler failed while compiling java_generator.h.
      C++ compiler failed while compiling java_plugin.cpp.
      C++ compiler failed while compiling java_generator.cpp.
  See the complete log at: file:///Users/cliffordberg/Library/grpc-java-1.1.2/compiler/build/tmp/compileJava_pluginExecutableJava_pluginCpp/output.txt

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 6.823 secs
Clifford-Bergs-MacBook-Pro:compiler cliffordberg$ echo $CXXFLAGS
-I/usr/local/include
Clifford-Bergs-MacBook-Pro:compiler cliffordberg$ echo $LDFLAGS
-L/usr/local/lib
Clifford-Bergs-MacBook-Pro:compiler cliffordberg$

**Comment by cliffbdf** [comment]
Hi -

Will it be possible to post a binary build of protoc for the Mac?

Very best,

Cliff
