### ISSUE TITLE
Broken link: from Benchmarking site to master dashboard

### ISSUE THREAD

**Issue by mohanraj-r** [grpc/grpc.github.io#451]
file: https://github.com/grpc/grpc.github.io/blob/master/docs/guides/benchmarking.md, [corresponding html page](http://www.grpc.io/docs/guides/benchmarking.html)

Link "Multi-language performance dashboard @master" refers to https://performance-dot-grpc-testing.appspot.com/explore?dashboard=5760820306771968 which shows an empty page with warnings : "No dashboard with ID 5760820306771968 was found."

Not sure how to find the right dashboard ID.

Also would be great to have Go lang in the performance dashboard.

**Comment by jtattermusch** [comment]
The link works now.
