### ISSUE TITLE
"Overview" in quickstart/tutorials seems to link to wrong page

### ISSUE THREAD

**Issue by ejona86** [grpc/grpc.github.io#462]
There are many references to "Overview" which link to [docs](http://www.grpc.io/docs/). However, they are in sentences like "Read a full explanation of this example and how gRPC works in our Overview" and "It assumes that you have read the Overview and are familiar with protocol buffers". That makes me think it used to point to the [guides](http://www.grpc.io/docs/guides/index.html), which provides gRPC concepts. Could the website redesign have messed up these references?

**Comment by LisaFC** [comment]
Fixed in https://github.com/grpc/grpc.github.io/pull/485, will close when it's merged.
