### ISSUE TITLE
Add search box to grpc.io

### ISSUE THREAD

**Issue by LisaFC** [grpc/grpc.github.io#495]
What it says up there.

**Comment by LisaFC** [comment]
This should be simple enough: http://lcarey0-l.dub.corp.google.com:4000/grpc.github.io/docs/search/?q=streaming

Though now to make the search box look less weird. We also presumably don't want ads on it, so will need to sort out the premium version.

**Comment by LisaFC** [comment]
OK, we can get ad-free custom search if we're using Google for Non-Profits, I *think* we can probably sort that via CNCF, I'm investigating.

**Comment by sanjaypujare** [comment]
Any update on this? Search is needed on grpc.io

**Comment by thisisnotapril** [comment]
Closing this issue for now; we are migrating to a new site soon and can revisit search then if still needed.
