### ISSUE TITLE
Missing php code gen tool install guide

### ISSUE THREAD

**Issue by netroby** [grpc/grpc.github.io#579]
Missing php code gen tool install guide
The section : Generating client code

https://grpc.io/docs/tutorials/basic/php.html#generating-client-code

Missing how to install php code gen tool.

https://github.com/grpc/grpc/issues/12714

And the generate command not working at all.

**Comment by jtattermusch** [comment]
@ZhouyihaiDing  seems like a good item for the fixit.

**Comment by ZhouyihaiDing** [comment]
grpc_php_plugin is updated in https://github.com/grpc/grpc.github.io/pull/593/files#diff-eb973ca5c5ad5a35f6b2cfa030dbcdffR158 and this PR is approved.
I think we can merge that PR and close this issue. But I don't have the accessibility for this repo to do those things @stanley-cheung .

**Comment by jtattermusch** [comment]
I merged the PR.
