### ISSUE TITLE
Invalid Node.js Dependency (Docs)

### ISSUE THREAD

**Issue by coreybutler** [grpc/grpc.github.io#584]
While exploring/teaching myself about gRPC, I came across https://grpc.io/docs/quickstart/node.html ([node.md](https://github.com/grpc/grpc.github.io/blob/master/docs/quickstart/node.md)), which states Node version 1.1 or higher is required. There is no such thing as Node `1.1`. 

Perhaps this was supposed to be `0.1.1`? Perhaps `4.1.1` or `6.1.1`? It makes a big difference since ECMAScript 2015 support didn't exist until later editions. The notes in the [node example](https://github.com/grpc/grpc/tree/master/examples/node) indicate version `0.12.x` is required. After the `0.13.x` branch, io.js was merged and Node official moved to the `4.x.x` versioning. 

Additionally, the `0.12.x` branch is no longer supported by the Node Foundation. 

Anyhow, clarity around the Node version requirement would be helpful for those of us who are just trying to understand the capabilities/envision how we'd implement gRPC.

**Comment by hsaliak** [comment]
@murgatroid99 could you clarify the version support?

**Comment by murgatroid99** [comment]
It should say that the minimum version is 4.0.0

**Comment by jtattermusch** [comment]
@murgatroid99, can you fix as part of of the fixit. Seems easy enough.
