### ISSUE TITLE
C# quick start Grpc.Tools.1.7.x vs Grpc.Tools.1.2.2

### ISSUE THREAD

**Issue by qbolec** [grpc/grpc.github.io#596]
Not sure what exactly went wrong while following the tutorial https://grpc.io/docs/quickstart/csharp.html but at some point the tutorial states I should run:
```
> packages\Grpc.Tools.1.7.x\tools\windows_x86\protoc.exe -I../../protos --csharp_out Greeter --grpc_out Greeter ../../protos/helloworld.proto --plugin=protoc-gen-grpc=packages/Grpc.Tools.1.7.x/tools/windows_x86/grpc_csharp_plugin.exe
```
but the packages directory contains Grpc.Tools.1.2.2 and not Grpc.Tools.1.2.2.
Moreover the content of generate_protos.bat also references Grp.Tools.1.2.2.
I am on v1.7.x branch, windows 10, Visual Studio Express 2015 for Windows Desktop.

**Comment by jtattermusch** [comment]
You're right that our example projects are out of date, we will update them soon. In the meantime, you can update the Grpc.Core and Grpc.Tools packages in the example projects yourself.
