### ISSUE TITLE
Errors section formatting issues

### ISSUE THREAD

**Issue by mugurm** [grpc/grpc.github.io#65]
The section describing errors at http://www.grpc.io/docs/guides/wire.html#errors appears incorrectly formatted.

**Comment by tr33house** [comment]
it looks like this issue has since been resolved. I don't see any errors.
![screencapture-grpc-io-docs](https://cloud.githubusercontent.com/assets/1892888/19953961/9e5ade8c-a130-11e6-9635-2e410014c817.png)

**Comment by tr33house** [comment]
proposing that we close this issue
