### ISSUE TITLE
Font color too light to read for vision impaired

### ISSUE THREAD

**Issue by gonzojive** [grpc/grpc.github.io#694]
My vision is not that great, so I find the gRPC website hard to read. May you please make the text black instead of medium gray? I believe the line that needs to change is the following:

https://github.com/grpc/grpc.github.io/blob/c02c68714292e9fe08171a0861f6df03a628c7a3/_sass/base/_colors.scss#L27

**Comment by carl-mastrangelo** [comment]
Can you take a screen cap of where you see this?  Most of the text appears close to black

**Comment by gonzojive** [comment]
See the difference below (based on changing CSS in the browser).

![black](https://user-images.githubusercontent.com/83831/41869365-a5c655aa-786d-11e8-8559-6aeb1c371162.png)

![medium gray](https://user-images.githubusercontent.com/83831/41869366-a5deba1e-786d-11e8-96be-73a3181ea7ff.png)
