### ISSUE TITLE
Broken links: from Benchmarking site under Performance testing design

### ISSUE THREAD

**Issue by derrickaw** [grpc/grpc.github.io#704]
Links are broken for both [WorkerService](https://github.com/grpc/grpc/blob/master/src/proto/grpc/testing/services.proto) and [BenchmarkService](https://github.com/grpc/grpc/blob/master/src/proto/grpc/testing/services.proto).

**Comment by carl-mastrangelo** [comment]
Hi @kpayson64  can you take a look?  It seems it was changed in https://github.com/grpc/grpc/commit/7a20c962dfa547a7b7fc1a49e4ff3b2e92eae5e1
