### ISSUE TITLE
Web Quickstart for Echo example is broken

### ISSUE THREAD

**Issue by annieoakley** [grpc/grpc.github.io#755]
When I try to follow the steps on https://grpc.io/docs/quickstart/web.html, `$ docker-compose pull prereqs common node-server envoy commonjs-client` fails for node-server:

ERROR: for node-server  pull access denied for grpcweb/node-server, repository does not exist or may require 'docker login'
ERROR: pull access denied for grpcweb/node-server, repository does not exist or may require 'docker login'

I am logged in with Docker, so that is not the issue.

I believe a recent change https://github.com/grpc/grpc-web/commit/3f4cc9e1dc697275e1473739871e78dc85183380 may have caused this.

**Comment by annieoakley** [comment]
@stanley-cheung could you please take a quick look?

**Comment by stanley-cheung** [comment]
Sorry I forgot to re-push the docker images after the latest release. They are pushed now. So this should work now:

```
$ docker-compose pull prereqs common node-server envoy commonjs-client
$ docker-compose up -d node-server envoy commonjs-client
```

**Comment by jakepoz** [comment]
Confirmed, it works for me now!
