### ISSUE TITLE
Python documentation says "© Copyright 2015, Author."

### ISSUE THREAD

**Issue by nathanielmanistaatgoogle** [grpc/grpc.github.io#81]
At the bottom of http://www.grpc.io/grpc/python/.

I _think_ it should say "© Copyright 2015, The gRPC Authors.", but it's probably @LisaFC's and @mugurm's decision to make. It definitely shouldn't be individuals listed by name. It could be that we don't even want copyright notice on our documentation?

**Comment by nathanielmanistaatgoogle** [comment]
@soltanmm-google: what would it take to change our docs to say "the gRPC Python authors" in this way?

**Comment by soltanmm** [comment]
Our docs? As in these here: http://www.grpc.io/grpc/python/ ?

**Comment by nathanielmanistaatgoogle** [comment]
@soltanmm-google: yes, see at the bottom where it says "© Copyright 2016, Author."?

**Comment by nathanielmanistaatgoogle** [comment]
This was fixed in [grpc/grpc pull request 9203](https://github.com/grpc/grpc/pull/9203) and released in [the 1.1.0 documentation](https://github.com/grpc/grpc/pull/9565).
