### ISSUE TITLE
no command grpc_tools_ruby_protoc

### ISSUE THREAD

**Issue by quinn** [grpc/grpc.github.io#844]
There is no such command, and installing the grpc gem does not create it.

**Comment by carl-mastrangelo** [comment]
cc @apolcyn

**Comment by apolcyn** [comment]
This binary is provided not by the `grpc` gem but by the `grpc-tools` gem.

`gem install grpc-tools` would add `grpc_tools_ruby_protoc` (and `grpc_tools_ruby_protoc_plugin`) executables to your PATH.

**Comment by quinn** [comment]
thanks!
